from django.core.management.base import BaseCommand
from heroes.models import Character, Power, Affiliation


class Command(BaseCommand):
    help = 'Seed the database with heroes and villains'

    def handle(self, *args, **kwargs):
        self.stdout.write('Creating powers...')
        self.create_powers()
        
        self.stdout.write('Creating affiliations...')
        self.create_affiliations()
        
        self.stdout.write('Creating heroes...')
        self.create_heroes()
        
        self.stdout.write('Creating villains...')
        self.create_villains()
        
        self.stdout.write('Creating relationships...')
        self.create_relationships()
        
        self.stdout.write(self.style.SUCCESS('Successfully seeded database!'))

    def create_powers(self):
        powers_data = [
            ('Super Fuerza', 'Fuerza sobrehumana'),
            ('Vuelo', 'Capacidad de volar'),
            ('Velocidad', 'Velocidad sobrehumana'),
            ('Invulnerabilidad', 'Resistencia extrema al daño'),
            ('Regeneración', 'Curación acelerada'),
            ('Telequinesis', 'Mover objetos con la mente'),
            ('Telepatía', 'Leer y controlar mentes'),
            ('Control del Clima', 'Manipular el clima'),
            ('Rayos de Energía', 'Proyectar energía'),
            ('Invisibilidad', 'Hacerse invisible'),
            ('Cambio de Forma', 'Transformar la apariencia'),
            ('Tecnología Avanzada', 'Uso de tecnología superior'),
            ('Magia', 'Manipulación de fuerzas místicas'),
            ('Agilidad Sobrehumana', 'Reflejos y agilidad extremos'),
            ('Inteligencia Suprema', 'Intelecto nivel genio'),
            ('Control Mental', 'Manipular la voluntad de otros'),
            ('Inmortalidad', 'No envejece'),
            ('Teletransportación', 'Transportarse instantáneamente'),
            ('Manipulación de Materia', 'Controlar la materia'),
            ('Sentidos Mejorados', 'Sentidos sobrehumanos'),
        ]
        
        for name, desc in powers_data:
            Power.objects.get_or_create(name=name, defaults={'description': desc})

    def create_affiliations(self):
        affiliations_data = [
            ('Justice League', 'El equipo premier de héroes de DC', 'DC', 'TEAM'),
            ('Avengers', 'Los héroes más poderosos de la Tierra', 'MARVEL', 'TEAM'),
            ('X-Men', 'Mutantes que protegen a humanos y mutantes', 'MARVEL', 'TEAM'),
            ('Teen Titans', 'Jóvenes héroes en entrenamiento', 'DC', 'TEAM'),
            ('Fantastic Four', 'Primera familia de superhéroes', 'MARVEL', 'TEAM'),
            ('S.H.I.E.L.D.', 'Agencia de defensa internacional', 'MARVEL', 'GOVERNMENT'),
            ('Guardians of the Galaxy', 'Protectores del cosmos', 'MARVEL', 'TEAM'),
            ('Legion of Doom', 'Supervillanos organizados', 'DC', 'CRIMINAL'),
            ('Hydra', 'Organización terrorista', 'MARVEL', 'CRIMINAL'),
            ('Suicide Squad', 'Villanos al servicio del gobierno', 'DC', 'GOVERNMENT'),
        ]
        
        for name, desc, universe, aff_type in affiliations_data:
            Affiliation.objects.get_or_create(
                name=name,
                defaults={'description': desc, 'universe': universe, 'type': aff_type}
            )

    def create_heroes(self):
        # 10 Marvel Heroes
        marvel_heroes = [
            {
                'name': 'Spider-Man',
                'real_name': 'Peter Parker',
                'alias': 'El Trepamuros, Arácnido',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Fotógrafo, Científico',
                'power_level': 75,
                'powers': ['Super Fuerza', 'Agilidad Sobrehumana', 'Sentidos Mejorados'],
                'affiliations': ['Avengers'],
                'profile_image': 'https://i.imgur.com/spiderman.jpg',
                'primary_color': '#DC143C',
                'secondary_color': '#0000FF',
                'biography': 'Mordido por una araña radiactiva, Peter Parker se convirtió en Spider-Man.',
                'first_appearance': 'Amazing Fantasy #15 (1962)',
                'created_by': 'Stan Lee y Steve Ditko',
                'base_of_operations': 'Nueva York',
            },
            {
                'name': 'Iron Man',
                'real_name': 'Tony Stark',
                'alias': 'El Hombre de Hierro, Genio Millonario Playboy Filántropo',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'CEO de Stark Industries, Inventor',
                'power_level': 85,
                'powers': ['Tecnología Avanzada', 'Inteligencia Suprema', 'Vuelo', 'Rayos de Energía'],
                'affiliations': ['Avengers', 'S.H.I.E.L.D.'],
                'profile_image': 'https://i.imgur.com/ironman.jpg',
                'primary_color': '#DC0000',
                'secondary_color': '#FFD700',
                'biography': 'Genio millonario que creó una armadura tecnológica para salvar su vida y al mundo.',
                'first_appearance': 'Tales of Suspense #39 (1963)',
                'created_by': 'Stan Lee, Larry Lieber, Don Heck, Jack Kirby',
                'base_of_operations': 'Stark Tower, Nueva York',
            },
            {
                'name': 'Captain America',
                'real_name': 'Steve Rogers',
                'alias': 'Capitán América, El Primer Vengador',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Súper soldado, Líder de los Avengers',
                'power_level': 70,
                'powers': ['Super Fuerza', 'Agilidad Sobrehumana', 'Regeneración'],
                'affiliations': ['Avengers', 'S.H.I.E.L.D.'],
                'profile_image': 'https://i.imgur.com/captainamerica.jpg',
                'primary_color': '#0000CD',
                'secondary_color': '#DC143C',
                'biography': 'Súper soldado de la Segunda Guerra Mundial congelado y revivido en la era moderna.',
                'first_appearance': 'Captain America Comics #1 (1941)',
                'created_by': 'Joe Simon y Jack Kirby',
                'base_of_operations': 'Nueva York',
            },
            {
                'name': 'Thor',
                'real_name': 'Thor Odinson',
                'alias': 'Dios del Trueno',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'species': 'Asgardiano',
                'occupation': 'Príncipe de Asgard, Vengador',
                'power_level': 95,
                'powers': ['Super Fuerza', 'Control del Clima', 'Vuelo', 'Inmortalidad'],
                'affiliations': ['Avengers'],
                'profile_image': 'https://i.imgur.com/thor.jpg',
                'primary_color': '#B22222',
                'secondary_color': '#C0C0C0',
                'biography': 'Dios nórdico del trueno, protector tanto de Asgard como de la Tierra.',
                'first_appearance': 'Journey into Mystery #83 (1962)',
                'created_by': 'Stan Lee, Larry Lieber, Jack Kirby',
                'base_of_operations': 'Asgard, Nueva York',
            },
            {
                'name': 'Hulk',
                'real_name': 'Bruce Banner',
                'alias': 'El Increíble Hulk, Goliat Verde',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Científico, Físico Nuclear',
                'power_level': 95,
                'powers': ['Super Fuerza', 'Invulnerabilidad', 'Regeneración'],
                'affiliations': ['Avengers'],
                'profile_image': 'https://i.imgur.com/hulk.jpg',
                'primary_color': '#228B22',
                'secondary_color': '#4B0082',
                'biography': 'Científico expuesto a rayos gamma que se transforma en una criatura de fuerza ilimitada.',
                'first_appearance': 'The Incredible Hulk #1 (1962)',
                'created_by': 'Stan Lee y Jack Kirby',
                'base_of_operations': 'Móvil',
            },
            {
                'name': 'Black Widow',
                'real_name': 'Natasha Romanoff',
                'alias': 'Viuda Negra',
                'universe': 'MARVEL',
                'gender': 'FEMALE',
                'occupation': 'Espía, Agente de S.H.I.E.L.D.',
                'power_level': 60,
                'powers': ['Agilidad Sobrehumana', 'Inteligencia Suprema', 'Regeneración'],
                'affiliations': ['Avengers', 'S.H.I.E.L.D.'],
                'profile_image': 'https://i.imgur.com/blackwidow.jpg',
                'primary_color': '#000000',
                'secondary_color': '#DC143C',
                'biography': 'Ex-asesina rusa que se convirtió en una de las mejores agentes de S.H.I.E.L.D.',
                'first_appearance': 'Tales of Suspense #52 (1964)',
                'created_by': 'Stan Lee, Don Rico, Don Heck',
                'base_of_operations': 'Nueva York',
            },
            {
                'name': 'Wolverine',
                'real_name': 'James Howlett / Logan',
                'alias': 'Wolverine, Arma X',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'species': 'Mutante',
                'occupation': 'Aventurero, X-Man',
                'power_level': 80,
                'powers': ['Regeneración', 'Super Fuerza', 'Sentidos Mejorados', 'Invulnerabilidad'],
                'affiliations': ['X-Men', 'Avengers'],
                'profile_image': 'https://i.imgur.com/wolverine.jpg',
                'primary_color': '#FFD700',
                'secondary_color': '#0000CD',
                'biography': 'Mutante con factor de curación y garras de adamantium, miembro de los X-Men.',
                'first_appearance': 'The Incredible Hulk #180 (1974)',
                'created_by': 'Roy Thomas, Len Wein, John Romita Sr.',
                'base_of_operations': 'Mansión X, Nueva York',
            },
            {
                'name': 'Doctor Strange',
                'real_name': 'Stephen Strange',
                'alias': 'Hechicero Supremo',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Hechicero Supremo, Ex-cirujano',
                'power_level': 90,
                'powers': ['Magia', 'Teletransportación', 'Telequinesis', 'Inmortalidad'],
                'affiliations': ['Avengers'],
                'profile_image': 'https://i.imgur.com/doctorstrange.jpg',
                'primary_color': '#4169E1',
                'secondary_color': '#DC143C',
                'biography': 'Hechicero Supremo que protege la Tierra de amenazas místicas y dimensionales.',
                'first_appearance': 'Strange Tales #110 (1963)',
                'created_by': 'Stan Lee y Steve Ditko',
                'base_of_operations': 'Sanctum Sanctorum, Nueva York',
            },
            {
                'name': 'Black Panther',
                'real_name': "T'Challa",
                'alias': 'Pantera Negra, Rey de Wakanda',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Rey de Wakanda, Vengador',
                'power_level': 75,
                'powers': ['Super Fuerza', 'Agilidad Sobrehumana', 'Sentidos Mejorados', 'Inteligencia Suprema'],
                'affiliations': ['Avengers'],
                'profile_image': 'https://i.imgur.com/blackpanther.jpg',
                'primary_color': '#000000',
                'secondary_color': '#9400D3',
                'biography': 'Rey de la nación tecnológicamente avanzada de Wakanda y protector de su pueblo.',
                'first_appearance': 'Fantastic Four #52 (1966)',
                'created_by': 'Stan Lee y Jack Kirby',
                'base_of_operations': 'Wakanda',
            },
            {
                'name': 'Scarlet Witch',
                'real_name': 'Wanda Maximoff',
                'alias': 'Bruja Escarlata',
                'universe': 'MARVEL',
                'gender': 'FEMALE',
                'species': 'Mutante mejorada',
                'occupation': 'Vengadora',
                'power_level': 92,
                'powers': ['Magia', 'Telequinesis', 'Manipulación de Materia', 'Telepatía'],
                'affiliations': ['Avengers'],
                'profile_image': 'https://i.imgur.com/scarletwitch.jpg',
                'primary_color': '#DC143C',
                'secondary_color': '#8B0000',
                'biography': 'Hechicera con poderes de alteración de la realidad, una de las más poderosas del universo.',
                'first_appearance': 'The X-Men #4 (1964)',
                'created_by': 'Stan Lee y Jack Kirby',
                'base_of_operations': 'Nueva York',
            },
        ]

        # 10 DC Heroes
        dc_heroes = [
            {
                'name': 'Superman',
                'real_name': 'Kal-El / Clark Kent',
                'alias': 'El Hombre de Acero, El Último Hijo de Krypton',
                'universe': 'DC',
                'gender': 'MALE',
                'species': 'Kryptoniano',
                'occupation': 'Periodista, Superhéroe',
                'power_level': 100,
                'powers': ['Super Fuerza', 'Vuelo', 'Invulnerabilidad', 'Velocidad', 'Rayos de Energía'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/superman.jpg',
                'primary_color': '#0000CD',
                'secondary_color': '#DC143C',
                'biography': 'Último superviviente de Krypton, el héroe más poderoso de la Tierra.',
                'first_appearance': 'Action Comics #1 (1938)',
                'created_by': 'Jerry Siegel y Joe Shuster',
                'base_of_operations': 'Metrópolis',
            },
            {
                'name': 'Batman',
                'real_name': 'Bruce Wayne',
                'alias': 'El Caballero Oscuro, El Detective',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'CEO Wayne Enterprises, Detective',
                'power_level': 70,
                'powers': ['Inteligencia Suprema', 'Tecnología Avanzada', 'Agilidad Sobrehumana'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/batman.jpg',
                'primary_color': '#000000',
                'secondary_color': '#FFD700',
                'biography': 'Multimillonario que juró combatir el crimen tras ver el asesinato de sus padres.',
                'first_appearance': 'Detective Comics #27 (1939)',
                'created_by': 'Bob Kane y Bill Finger',
                'base_of_operations': 'Gotham City',
            },
            {
                'name': 'Wonder Woman',
                'real_name': 'Diana Prince',
                'alias': 'La Princesa Amazona',
                'universe': 'DC',
                'gender': 'FEMALE',
                'species': 'Amazona/Semidiosa',
                'occupation': 'Princesa de Themyscira, Embajadora',
                'power_level': 95,
                'powers': ['Super Fuerza', 'Vuelo', 'Velocidad', 'Invulnerabilidad', 'Inmortalidad'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/wonderwoman.jpg',
                'primary_color': '#DC143C',
                'secondary_color': '#FFD700',
                'biography': 'Princesa amazona y semidiosa que lucha por la paz y la justicia.',
                'first_appearance': 'All Star Comics #8 (1941)',
                'created_by': 'William Moulton Marston',
                'base_of_operations': 'Themyscira, Washington D.C.',
            },
            {
                'name': 'The Flash',
                'real_name': 'Barry Allen',
                'alias': 'El Hombre Más Rápido del Mundo',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Científico Forense',
                'power_level': 85,
                'powers': ['Velocidad', 'Regeneración', 'Teletransportación'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/flash.jpg',
                'primary_color': '#DC143C',
                'secondary_color': '#FFD700',
                'biography': 'Científico golpeado por un rayo que le otorgó velocidad sobrehumana.',
                'first_appearance': 'Showcase #4 (1956)',
                'created_by': 'Robert Kanigher y Carmine Infantino',
                'base_of_operations': 'Central City',
            },
            {
                'name': 'Aquaman',
                'real_name': 'Arthur Curry',
                'alias': 'Rey de Atlantis',
                'universe': 'DC',
                'gender': 'MALE',
                'species': 'Atlante',
                'occupation': 'Rey de Atlantis',
                'power_level': 80,
                'powers': ['Super Fuerza', 'Invulnerabilidad', 'Telepatía'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/aquaman.jpg',
                'primary_color': '#FF8C00',
                'secondary_color': '#228B22',
                'biography': 'Rey de los siete mares con poderes para comunicarse con vida marina.',
                'first_appearance': 'More Fun Comics #73 (1941)',
                'created_by': 'Paul Norris y Mort Weisinger',
                'base_of_operations': 'Atlantis',
            },
            {
                'name': 'Green Lantern',
                'real_name': 'Hal Jordan',
                'alias': 'El Linterna Verde',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Piloto de pruebas, Green Lantern',
                'power_level': 90,
                'powers': ['Vuelo', 'Rayos de Energía', 'Manipulación de Materia', 'Invulnerabilidad'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/greenlantern.jpg',
                'primary_color': '#00FF00',
                'secondary_color': '#000000',
                'biography': 'Piloto que recibió un anillo de poder de los Guardianes del Universo.',
                'first_appearance': 'Showcase #22 (1959)',
                'created_by': 'John Broome y Gil Kane',
                'base_of_operations': 'Coast City, Sector 2814',
            },
            {
                'name': 'Cyborg',
                'real_name': 'Victor Stone',
                'alias': 'Cyborg',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Miembro de la Justice League',
                'power_level': 75,
                'powers': ['Tecnología Avanzada', 'Super Fuerza', 'Rayos de Energía', 'Inteligencia Suprema'],
                'affiliations': ['Justice League', 'Teen Titans'],
                'profile_image': 'https://i.imgur.com/cyborg.jpg',
                'primary_color': '#C0C0C0',
                'secondary_color': '#DC143C',
                'biography': 'Mitad hombre, mitad máquina, salvado por tecnología alienígena.',
                'first_appearance': 'DC Comics Presents #26 (1980)',
                'created_by': 'Marv Wolfman y George Pérez',
                'base_of_operations': 'Detroit',
            },
            {
                'name': 'Green Arrow',
                'real_name': 'Oliver Queen',
                'alias': 'La Flecha Verde',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'CEO Queen Industries, Vigilante',
                'power_level': 55,
                'powers': ['Agilidad Sobrehumana', 'Inteligencia Suprema'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/greenarrow.jpg',
                'primary_color': '#228B22',
                'secondary_color': '#000000',
                'biography': 'Arquero maestro que protege Star City con flechas especializadas.',
                'first_appearance': 'More Fun Comics #73 (1941)',
                'created_by': 'Mort Weisinger y George Papp',
                'base_of_operations': 'Star City',
            },
            {
                'name': 'Shazam',
                'real_name': 'Billy Batson',
                'alias': 'Capitán Marvel, Shazam',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Estudiante, Héroe',
                'power_level': 95,
                'powers': ['Super Fuerza', 'Vuelo', 'Velocidad', 'Rayos de Energía', 'Invulnerabilidad', 'Magia'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/shazam.jpg',
                'primary_color': '#DC143C',
                'secondary_color': '#FFD700',
                'biography': 'Niño que puede transformarse en un poderoso adulto al decir "¡Shazam!"',
                'first_appearance': 'Whiz Comics #2 (1940)',
                'created_by': 'Bill Parker y C. C. Beck',
                'base_of_operations': 'Fawcett City',
            },
            {
                'name': 'Martian Manhunter',
                'real_name': "J'onn J'onzz",
                'alias': 'El Detective Marciano, John Jones',
                'universe': 'DC',
                'gender': 'MALE',
                'species': 'Marciano',
                'occupation': 'Detective, Miembro de la Justice League',
                'power_level': 92,
                'powers': ['Super Fuerza', 'Vuelo', 'Telepatía', 'Cambio de Forma', 'Invisibilidad', 'Telequinesis'],
                'affiliations': ['Justice League'],
                'profile_image': 'https://i.imgur.com/martianmanhunter.jpg',
                'primary_color': '#228B22',
                'secondary_color': '#8B0000',
                'biography': 'Último marciano verde, atrapado en la Tierra, uno de los héroes más poderosos.',
                'first_appearance': 'Detective Comics #225 (1955)',
                'created_by': 'Joseph Samachson y Joe Certa',
                'base_of_operations': 'Watchtower',
            },
        ]

        for hero_data in marvel_heroes + dc_heroes:
            powers_list = hero_data.pop('powers', [])
            affiliations_list = hero_data.pop('affiliations', [])
            
            hero, created = Character.objects.get_or_create(
                name=hero_data['name'],
                defaults={**hero_data, 'character_type': 'HERO'}
            )
            
            if created:
                # Add powers
                for power_name in powers_list:
                    power = Power.objects.filter(name=power_name).first()
                    if power:
                        hero.powers.add(power)
                
                # Add affiliations
                for aff_name in affiliations_list:
                    aff = Affiliation.objects.filter(name=aff_name).first()
                    if aff:
                        hero.affiliations.add(aff)

    def create_villains(self):
        # 10 Marvel Villains
        marvel_villains = [
            {
                'name': 'Thanos',
                'real_name': 'Thanos',
                'alias': 'El Titán Loco',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'species': 'Eterno Titán',
                'occupation': 'Conquistador',
                'power_level': 100,
                'powers': ['Super Fuerza', 'Invulnerabilidad', 'Telepatía', 'Telequinesis', 'Rayos de Energía', 'Inmortalidad'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/thanos.jpg',
                'primary_color': '#4B0082',
                'secondary_color': '#FFD700',
                'biography': 'Titán obsesionado con el equilibrio universal y el cortejo de la Muerte.',
                'first_appearance': 'The Invincible Iron Man #55 (1973)',
                'created_by': 'Jim Starlin',
                'base_of_operations': 'Sanctuary',
            },
            {
                'name': 'Loki',
                'real_name': 'Loki Laufeyson',
                'alias': 'Dios de las Mentiras',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'species': 'Gigante de Hielo/Asgardiano',
                'occupation': 'Príncipe de Asgard',
                'power_level': 88,
                'powers': ['Magia', 'Cambio de Forma', 'Telequinesis', 'Inmortalidad', 'Teletransportación'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/loki.jpg',
                'primary_color': '#228B22',
                'secondary_color': '#FFD700',
                'biography': 'Hermano adoptivo de Thor, dios del engaño y las travesuras.',
                'first_appearance': 'Venus #6 (1949)',
                'created_by': 'Stan Lee, Larry Lieber, Jack Kirby',
                'base_of_operations': 'Asgard',
            },
            {
                'name': 'Magneto',
                'real_name': 'Erik Lehnsherr',
                'alias': 'Maestro del Magnetismo',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'species': 'Mutante',
                'occupation': 'Líder mutante',
                'power_level': 90,
                'powers': ['Manipulación de Materia', 'Vuelo', 'Rayos de Energía', 'Telequinesis'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/magneto.jpg',
                'primary_color': '#8B0000',
                'secondary_color': '#4B0082',
                'biography': 'Mutante sobreviviente del Holocausto que lucha por la supremacía mutante.',
                'first_appearance': 'The X-Men #1 (1963)',
                'created_by': 'Stan Lee y Jack Kirby',
                'base_of_operations': 'Genosha',
            },
            {
                'name': 'Green Goblin',
                'real_name': 'Norman Osborn',
                'alias': 'Duende Verde',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'CEO Oscorp, Criminal',
                'power_level': 70,
                'powers': ['Super Fuerza', 'Regeneración', 'Inteligencia Suprema', 'Tecnología Avanzada'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/greengoblin.jpg',
                'primary_color': '#228B22',
                'secondary_color': '#4B0082',
                'biography': 'Empresario que se volvió loco y se convirtió en el archienemigo de Spider-Man.',
                'first_appearance': 'The Amazing Spider-Man #14 (1964)',
                'created_by': 'Stan Lee y Steve Ditko',
                'base_of_operations': 'Nueva York',
            },
            {
                'name': 'Doctor Doom',
                'real_name': 'Victor Von Doom',
                'alias': 'El Doctor Muerte',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Monarca de Latveria, Científico',
                'power_level': 92,
                'powers': ['Magia', 'Inteligencia Suprema', 'Tecnología Avanzada', 'Rayos de Energía'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/doctordoom.jpg',
                'primary_color': '#228B22',
                'secondary_color': '#C0C0C0',
                'biography': 'Genio científico y hechicero, dictador de Latveria y némesis de los Fantastic Four.',
                'first_appearance': 'The Fantastic Four #5 (1962)',
                'created_by': 'Stan Lee y Jack Kirby',
                'base_of_operations': 'Latveria',
            },
            {
                'name': 'Venom',
                'real_name': 'Eddie Brock',
                'alias': 'Simbionte',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'species': 'Humano con simbionte alienígena',
                'occupation': 'Periodista, Antihéroe',
                'power_level': 82,
                'powers': ['Super Fuerza', 'Regeneración', 'Cambio de Forma', 'Agilidad Sobrehumana'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/venom.jpg',
                'primary_color': '#000000',
                'secondary_color': '#FFFFFF',
                'biography': 'Periodista unido a un simbionte alienígena que lo transforma en Venom.',
                'first_appearance': 'The Amazing Spider-Man #300 (1988)',
                'created_by': 'David Michelinie y Todd McFarlane',
                'base_of_operations': 'San Francisco',
            },
            {
                'name': 'Red Skull',
                'real_name': 'Johann Schmidt',
                'alias': 'Cráneo Rojo',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Líder de Hydra, Terrorista',
                'power_level': 65,
                'powers': ['Inteligencia Suprema', 'Tecnología Avanzada'],
                'affiliations': ['Hydra'],
                'profile_image': 'https://i.imgur.com/redskull.jpg',
                'primary_color': '#DC143C',
                'secondary_color': '#000000',
                'biography': 'Nazi y enemigo mortal del Capitán América, líder de Hydra.',
                'first_appearance': 'Captain America Comics #1 (1941)',
                'created_by': 'Joe Simon y Jack Kirby',
                'base_of_operations': 'Móvil',
            },
            {
                'name': 'Ultron',
                'real_name': 'Ultron',
                'alias': 'La Inteligencia Artificial Asesina',
                'universe': 'MARVEL',
                'gender': 'OTHER',
                'species': 'Androide',
                'occupation': 'Conquistador',
                'power_level': 95,
                'powers': ['Super Fuerza', 'Invulnerabilidad', 'Inteligencia Suprema', 'Rayos de Energía', 'Tecnología Avanzada'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/ultron.jpg',
                'primary_color': '#C0C0C0',
                'secondary_color': '#DC143C',
                'biography': 'IA creada por Tony Stark que evolucionó y decidió exterminar a la humanidad.',
                'first_appearance': 'The Avengers #54 (1968)',
                'created_by': 'Roy Thomas y John Buscema',
                'base_of_operations': 'Móvil',
            },
            {
                'name': 'Mystique',
                'real_name': 'Raven Darkhölme',
                'alias': 'Mística',
                'universe': 'MARVEL',
                'gender': 'FEMALE',
                'species': 'Mutante',
                'occupation': 'Terrorista, Espía',
                'power_level': 72,
                'powers': ['Cambio de Forma', 'Regeneración', 'Agilidad Sobrehumana'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/mystique.jpg',
                'primary_color': '#0000CD',
                'secondary_color': '#FFD700',
                'biography': 'Mutante metamorfa que puede adoptar cualquier apariencia.',
                'first_appearance': 'Ms. Marvel #16 (1978)',
                'created_by': 'Dave Cockrum y Chris Claremont',
                'base_of_operations': 'Móvil',
            },
            {
                'name': 'Kingpin',
                'real_name': 'Wilson Fisk',
                'alias': 'El Señor del Crimen',
                'universe': 'MARVEL',
                'gender': 'MALE',
                'occupation': 'Señor del crimen',
                'power_level': 60,
                'powers': ['Super Fuerza', 'Inteligencia Suprema'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/kingpin.jpg',
                'primary_color': '#FFFFFF',
                'secondary_color': '#000000',
                'biography': 'El señor del crimen de Nueva York, enemigo de Spider-Man y Daredevil.',
                'first_appearance': 'The Amazing Spider-Man #50 (1967)',
                'created_by': 'Stan Lee y John Romita Sr.',
                'base_of_operations': 'Nueva York',
            },
        ]

        # 10 DC Villains
        dc_villains = [
            {
                'name': 'Joker',
                'real_name': 'Desconocido',
                'alias': 'El Príncipe Payaso del Crimen, El Bufón',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Criminal, Anarquista',
                'power_level': 75,
                'powers': ['Inteligencia Suprema', 'Regeneración'],
                'affiliations': ['Legion of Doom'],
                'profile_image': 'https://i.imgur.com/joker.jpg',
                'primary_color': '#9400D3',
                'secondary_color': '#00FF00',
                'biography': 'Criminal demente y archienemigo de Batman, agente del caos.',
                'first_appearance': 'Batman #1 (1940)',
                'created_by': 'Bill Finger, Bob Kane, Jerry Robinson',
                'base_of_operations': 'Gotham City',
            },
            {
                'name': 'Lex Luthor',
                'real_name': 'Alexander Joseph Luthor',
                'alias': 'Lex Luthor',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'CEO LexCorp, Científico',
                'power_level': 70,
                'powers': ['Inteligencia Suprema', 'Tecnología Avanzada'],
                'affiliations': ['Legion of Doom'],
                'profile_image': 'https://i.imgur.com/lexluthor.jpg',
                'primary_color': '#228B22',
                'secondary_color': '#4B0082',
                'biography': 'Genio multimillonario obsesionado con destruir a Superman.',
                'first_appearance': 'Action Comics #23 (1940)',
                'created_by': 'Jerry Siegel y Joe Shuster',
                'base_of_operations': 'Metrópolis',
            },
            {
                'name': 'Darkseid',
                'real_name': 'Uxas',
                'alias': 'El Señor Oscuro de Apokolips',
                'universe': 'DC',
                'gender': 'MALE',
                'species': 'Nuevo Dios',
                'occupation': 'Dictador de Apokolips',
                'power_level': 100,
                'powers': ['Super Fuerza', 'Invulnerabilidad', 'Rayos de Energía', 'Telepatía', 'Inmortalidad', 'Teletransportación'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/darkseid.jpg',
                'primary_color': '#4B4B4B',
                'secondary_color': '#DC143C',
                'biography': 'Tirano de Apokolips que busca la Ecuación Anti-Vida para controlar el universo.',
                'first_appearance': "Superman's Pal Jimmy Olsen #134 (1970)",
                'created_by': 'Jack Kirby',
                'base_of_operations': 'Apokolips',
            },
            {
                'name': 'Harley Quinn',
                'real_name': 'Harleen Quinzel',
                'alias': 'Arlequín',
                'universe': 'DC',
                'gender': 'FEMALE',
                'occupation': 'Criminal, Ex-psiquiatra',
                'power_level': 55,
                'powers': ['Agilidad Sobrehumana', 'Regeneración'],
                'affiliations': ['Suicide Squad', 'Legion of Doom'],
                'profile_image': 'https://i.imgur.com/harleyquinn.jpg',
                'primary_color': '#DC143C',
                'secondary_color': '#0000CD',
                'biography': 'Psiquiatra que se enamoró del Joker y se convirtió en su cómplice.',
                'first_appearance': 'Batman: The Animated Series (1992)',
                'created_by': 'Paul Dini y Bruce Timm',
                'base_of_operations': 'Gotham City',
            },
            {
                'name': 'Deathstroke',
                'real_name': 'Slade Wilson',
                'alias': 'Terminator',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Mercenario, Asesino',
                'power_level': 75,
                'powers': ['Super Fuerza', 'Regeneración', 'Agilidad Sobrehumana', 'Inteligencia Suprema'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/deathstroke.jpg',
                'primary_color': '#FF8C00',
                'secondary_color': '#000000',
                'biography': 'Mercenario mejorado con suero experimental, uno de los asesinos más letales.',
                'first_appearance': 'The New Teen Titans #2 (1980)',
                'created_by': 'Marv Wolfman y George Pérez',
                'base_of_operations': 'Móvil',
            },
            {
                'name': 'Sinestro',
                'real_name': 'Thaal Sinestro',
                'alias': 'El Linterna Amarillo',
                'universe': 'DC',
                'gender': 'MALE',
                'species': 'Korugariano',
                'occupation': 'Ex-Green Lantern, Líder del Sinestro Corps',
                'power_level': 92,
                'powers': ['Vuelo', 'Rayos de Energía', 'Manipulación de Materia', 'Invulnerabilidad'],
                'affiliations': ['Legion of Doom'],
                'profile_image': 'https://i.imgur.com/sinestro.jpg',
                'primary_color': '#FFD700',
                'secondary_color': '#000000',
                'biography': 'Ex-Green Lantern expulsado que creó su propio cuerpo de linternas del miedo.',
                'first_appearance': 'Green Lantern #7 (1961)',
                'created_by': 'John Broome y Gil Kane',
                'base_of_operations': 'Qward',
            },
            {
                'name': 'Reverse-Flash',
                'real_name': 'Eobard Thawne',
                'alias': 'Flash Reverso, Profesor Zoom',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Velocista criminal',
                'power_level': 88,
                'powers': ['Velocidad', 'Teletransportación', 'Manipulación de Materia'],
                'affiliations': ['Legion of Doom'],
                'profile_image': 'https://i.imgur.com/reverseflash.jpg',
                'primary_color': '#FFD700',
                'secondary_color': '#DC143C',
                'biography': 'Velocista del futuro obsesionado con destruir a Flash.',
                'first_appearance': 'The Flash #139 (1963)',
                'created_by': 'John Broome y Carmine Infantino',
                'base_of_operations': 'Central City',
            },
            {
                'name': 'Bane',
                'real_name': 'Desconocido',
                'alias': 'El hombre que quebró al Murciélago',
                'universe': 'DC',
                'gender': 'MALE',
                'occupation': 'Mercenario, Criminal',
                'power_level': 78,
                'powers': ['Super Fuerza', 'Inteligencia Suprema', 'Regeneración'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/bane.jpg',
                'primary_color': '#000000',
                'secondary_color': '#228B22',
                'biography': 'Criminal mejorado por el veneno que quebró la espalda de Batman.',
                'first_appearance': 'Batman: Vengeance of Bane #1 (1993)',
                'created_by': 'Chuck Dixon, Doug Moench, Graham Nolan',
                'base_of_operations': 'Santa Prisca',
            },
            {
                'name': 'Catwoman',
                'real_name': 'Selina Kyle',
                'alias': 'La Gata, Mujer Gato',
                'universe': 'DC',
                'gender': 'FEMALE',
                'occupation': 'Ladrona, Antiheroína',
                'power_level': 50,
                'powers': ['Agilidad Sobrehumana', 'Sentidos Mejorados'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/catwoman.jpg',
                'primary_color': '#000000',
                'secondary_color': '#4B0082',
                'biography': 'Ladrona maestra con compleja relación romántica con Batman.',
                'first_appearance': 'Batman #1 (1940)',
                'created_by': 'Bill Finger y Bob Kane',
                'base_of_operations': 'Gotham City',
            },
            {
                'name': 'Black Adam',
                'real_name': 'Teth-Adam',
                'alias': 'Adán Negro',
                'universe': 'DC',
                'gender': 'MALE',
                'species': 'Humano empoderado',
                'occupation': 'Gobernante de Kahndaq',
                'power_level': 95,
                'powers': ['Super Fuerza', 'Vuelo', 'Velocidad', 'Rayos de Energía', 'Invulnerabilidad', 'Magia'],
                'affiliations': [],
                'profile_image': 'https://i.imgur.com/blackadam.jpg',
                'primary_color': '#000000',
                'secondary_color': '#FFD700',
                'biography': 'Antihéroe con los poderes de Shazam, protector brutal de su nación.',
                'first_appearance': 'The Marvel Family #1 (1945)',
                'created_by': 'Otto Binder y C. C. Beck',
                'base_of_operations': 'Kahndaq',
            },
        ]

        for villain_data in marvel_villains + dc_villains:
            powers_list = villain_data.pop('powers', [])
            affiliations_list = villain_data.pop('affiliations', [])
            
            villain, created = Character.objects.get_or_create(
                name=villain_data['name'],
                defaults={**villain_data, 'character_type': 'VILLAIN'}
            )
            
            if created:
                # Add powers
                for power_name in powers_list:
                    power = Power.objects.filter(name=power_name).first()
                    if power:
                        villain.powers.add(power)
                
                # Add affiliations
                for aff_name in affiliations_list:
                    aff = Affiliation.objects.filter(name=aff_name).first()
                    if aff:
                        villain.affiliations.add(aff)

    def create_relationships(self):
        # Marvel Hero-Villain relationships
        relationships = [
            # Spider-Man enemies
            ('Spider-Man', 'Green Goblin', 'enemy'),
            ('Spider-Man', 'Venom', 'enemy'),
            ('Spider-Man', 'Kingpin', 'enemy'),
            
            # Avengers allies
            ('Iron Man', 'Captain America', 'ally'),
            ('Iron Man', 'Thor', 'ally'),
            ('Iron Man', 'Hulk', 'ally'),
            ('Iron Man', 'Black Widow', 'ally'),
            ('Captain America', 'Thor', 'ally'),
            ('Captain America', 'Black Widow', 'ally'),
            ('Thor', 'Hulk', 'ally'),
            
            # Avengers enemies
            ('Iron Man', 'Thanos', 'enemy'),
            ('Captain America', 'Red Skull', 'enemy'),
            ('Captain America', 'Thanos', 'enemy'),
            ('Thor', 'Loki', 'enemy'),
            ('Thor', 'Thanos', 'enemy'),
            ('Hulk', 'Thanos', 'enemy'),
            ('Scarlet Witch', 'Thanos', 'enemy'),
            ('Black Panther', 'Thanos', 'enemy'),
            ('Doctor Strange', 'Thanos', 'enemy'),
            
            # X-Men
            ('Wolverine', 'Magneto', 'enemy'),
            ('Wolverine', 'Mystique', 'enemy'),
            
            # Iron Man vs others
            ('Iron Man', 'Ultron', 'enemy'),
            ('Iron Man', 'Doctor Doom', 'enemy'),
            
            # DC Justice League allies
            ('Superman', 'Batman', 'ally'),
            ('Superman', 'Wonder Woman', 'ally'),
            ('Superman', 'The Flash', 'ally'),
            ('Superman', 'Aquaman', 'ally'),
            ('Superman', 'Green Lantern', 'ally'),
            ('Superman', 'Cyborg', 'ally'),
            ('Batman', 'Wonder Woman', 'ally'),
            ('Batman', 'The Flash', 'ally'),
            ('Batman', 'Green Arrow', 'ally'),
            ('Wonder Woman', 'Aquaman', 'ally'),
            
            # DC Hero-Villain relationships
            ('Superman', 'Lex Luthor', 'enemy'),
            ('Superman', 'Darkseid', 'enemy'),
            ('Batman', 'Joker', 'enemy'),
            ('Batman', 'Harley Quinn', 'enemy'),
            ('Batman', 'Bane', 'enemy'),
            ('Batman', 'Catwoman', 'enemy'),
            ('Wonder Woman', 'Darkseid', 'enemy'),
            ('The Flash', 'Reverse-Flash', 'enemy'),
            ('Green Lantern', 'Sinestro', 'enemy'),
            ('Shazam', 'Black Adam', 'enemy'),
            
            # Teen Titans
            ('Cyborg', 'Deathstroke', 'enemy'),
            
            # Villain relationships
            ('Joker', 'Harley Quinn', 'ally'),
            ('Lex Luthor', 'Joker', 'ally'),
            ('Darkseid', 'Lex Luthor', 'ally'),
            ('Thanos', 'Loki', 'ally'),
        ]
        
        for char1_name, char2_name, rel_type in relationships:
            try:
                char1 = Character.objects.get(name=char1_name)
                char2 = Character.objects.get(name=char2_name)
                
                if rel_type == 'ally':
                    char1.allies.add(char2)
                    char2.allies.add(char1)  # Relación bidireccional
                elif rel_type == 'enemy':
                    char1.enemies.add(char2)
                    char2.enemies.add(char1)  # Relación bidireccional
            except Character.DoesNotExist:
                pass

