# Changes here will be overwritten by Copier
_commit: v0.18.1
_src_path: gh:sarthakjariwala/django-vite-inertia
allauth: true
database: postgresql
docker_dev: true
docker_prod: true
frontend: react
project_name: django-inertia
starter_kit: true
tailwind_css: true

